version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build: .
    container_name: api_service
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USER: admin
      DB_PASSWORD: secret
    volumes:
      - .:/app
    networks:
      - app_network
    entrypoint: ["/app/entrypoint.sh"]

volumes:
  postgres_data:

networks:
  app_network: